tap 'homebrew/cask-drivers'
tap 'epk/epk'
tap 'nicoverbruggen/homebrew-cask'
tap 'koekeishiya/formulae'             # yabai
tap 'yqrashawn/goku'                   # goku

brew 'antibody'
brew 'composer'
brew 'dnsmasq'
brew 'fzf'
brew 'gh'
brew 'goku'
brew 'mackup'
brew 'mas'
brew 'nginx'
brew 'node'
brew 'php'
brew 'php@7.3'
brew 'php@7.4'
brew 'starship'
brew 'thefuck'
brew 'trash'
brew 'tree'

cask '1password'
cask 'discord'
cask 'docker'
cask 'droplr'
cask 'fantastical'
cask 'firefox'
cask 'font-fira-code-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-sf-mono-nerd-font'
cask 'hammerspoon'
cask 'helo'
cask 'iterm2'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'logitech-options'
cask 'nordvpn'
cask 'paw'
cask 'phpmon'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'tableplus'
cask 'telegram'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'tower'
cask 'transmit'
cask 'visual-studio-code'

mas 'Bear Notes', id: 1091189122
mas 'Moom', id: 419330170
