brew 'composer'
brew 'mas'
brew 'node'
brew 'php'
brew 'php', restart_service: true
brew 'starship'
brew 'trash'
brew 'tree'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew "dnsmasq", restart_service: true
brew "nginx", restart_service: true

cask '1password'
cask 'discord'
cask 'docker'
cask 'droplr'
cask 'fantastical'
cask 'firefox'
cask 'iterm2'
cask 'kaleidoscope'
cask 'moom'
cask 'nordvpn'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'tableplus'
cask 'telegram'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'tower'
cask 'transmit'
cask 'visual-studio-code'

mas 'Bear Notes', id: 1091189122
