format = """
$directory$git_branch$git_status$line_break$character
"""

[character]
success_symbol = '[→](bold green)'
error_symbol = '[→](bold red)'

[directory]
truncation_length = 5

[git_status]
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'
