# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------

export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$DOTFILES/zsh/custom

export PATH=/opt/homebrew/bin:${PATH}
export PATH=/opt/homebrew/sbin:${PATH}
export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:/usr/local/sbin
export PATH=${PATH}:~/.composer/vendor/bin

export GOKU_EDN_CONFIG_FILE=$DOTFILES/karabiner/karabiner.edn


# ------------------------------------------------------------------------------
# General Settings
# ------------------------------------------------------------------------------

export LANG=en_US.UTF-8
export XDEBUG_CONFIG="idekey=VSCODE"
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_REPOSITORY="/opt/homebrew"
export EDITOR="vim"


# ------------------------------------------------------------------------------
# Znap
# https://github.com/marlonrichert/zsh-snap
# ------------------------------------------------------------------------------

# Download Znap, if it's not there yet.
[[ -f ~/.dotfiles/zsh/repos/znap/znap.zsh ]] ||
    git clone https://github.com/marlonrichert/zsh-snap.git ~/.dotfiles/zsh/repos/znap

source ~/.dotfiles/zsh/repos/znap/znap.zsh


# ------------------------------------------------------------------------------
# Starship Prompt
# https://starship.rs
# ------------------------------------------------------------------------------

znap eval starship 'starship init zsh'
znap prompt


# ------------------------------------------------------------------------------
# Plugins
# ------------------------------------------------------------------------------

# Autocomplete https://github.com/marlonrichert/zsh-autocomplete
znap source marlonrichert/zsh-autocomplete

# Autosuggestions https://github.com/zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-autosuggestions

# Syntax Highlighting https://github.com/zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-syntax-highlighting

# Tipz https://github.com/molovo/tipz
TIPZ_TEXT='💡 Aliased to:'
znap source molovo/tipz

# Artisan/Please Autocomplete
znap source laravel
znap source please


# ------------------------------------------------------------------------------
# Source External ZSH Files
# ------------------------------------------------------------------------------

source $DOTFILES/zsh/functions.zsh
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/private.zsh
