# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------

export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$DOTFILES/zsh/custom

export PATH=/opt/homebrew/bin:${PATH}
export PATH=/opt/homebrew/sbin:${PATH}
export PATH=${PATH}:~/.local/bin
export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:/usr/local/sbin
export PATH=~/.composer/vendor/bin:${PATH}
export PATH=~/.config/phpmon/bin:${PATH}

export GOKU_EDN_CONFIG_FILE=$DOTFILES/karabiner/karabiner.edn
export BAT_CONFIG_PATH="$DOTFILES/bat/bat.conf"


# ------------------------------------------------------------------------------
# General Settings
# ------------------------------------------------------------------------------

export LANG=en_US.UTF-8
export XDEBUG_CONFIG="idekey=VSCODE"
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_REPOSITORY="/opt/homebrew"
export HOMEBREW_NO_AUTO_UPDATE="1"
export EDITOR="vim"


# ------------------------------------------------------------------------------
# Starship Prompt
# https://starship.rs
# ------------------------------------------------------------------------------

eval "$(starship init zsh)"


# ------------------------------------------------------------------------------
# Antidote
# ------------------------------------------------------------------------------

source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load $DOTFILES/zsh/bundles.txt

sz() {
  rm $DOTFILES/zsh/bundles.zsh
  source $DOTFILES/zsh/zshrc
  echo 'Sourced zshrc'
}


# ------------------------------------------------------------------------------
# Laravel Herd
# ------------------------------------------------------------------------------

# Herd injected NVM configuration
export NVM_DIR="/Users/jason/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"

# Herd injected PHP binary.
export PATH="/Users/jason/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP 7.4 configuration.
export HERD_PHP_74_INI_SCAN_DIR="/Users/jason/Library/Application Support/Herd/config/php/74/"

# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/jason/Library/Application Support/Herd/config/php/81/"

# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/jason/Library/Application Support/Herd/config/php/82/"

# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/jason/Library/Application Support/Herd/config/php/83/"

# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/jason/Library/Application Support/Herd/config/php/84/"

# Herd injected PHP 8.5 configuration.
export HERD_PHP_85_INI_SCAN_DIR="/Users/jason/Library/Application Support/Herd/config/php/85/"